package com.works.model;
// Generated 25.Eyl.2019 00:10:58 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Bcomment generated by hbm2java
 */
@Entity
@Table(name = "bcomment", catalog = "foodtown")
public class Bcomment implements java.io.Serializable {

	private Integer bcid;
	private String bcname;
	private String bcmail;
	private String bcomment;
	private Integer bcommentid;

	public Bcomment() {
	}

	public Bcomment(String bcname, String bcmail, String bcomment, Integer bcommentid) {
		this.bcname = bcname;
		this.bcmail = bcmail;
		this.bcomment = bcomment;
		this.bcommentid = bcommentid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "bcid", unique = true, nullable = false)
	public Integer getBcid() {
		return this.bcid;
	}

	public void setBcid(Integer bcid) {
		this.bcid = bcid;
	}

	@Column(name = "bcname", length = 100)
	public String getBcname() {
		return this.bcname;
	}

	public void setBcname(String bcname) {
		this.bcname = bcname;
	}

	@Column(name = "bcmail")
	public String getBcmail() {
		return this.bcmail;
	}

	public void setBcmail(String bcmail) {
		this.bcmail = bcmail;
	}

	@Column(name = "bcomment", length = 65535)
	public String getBcomment() {
		return this.bcomment;
	}

	public void setBcomment(String bcomment) {
		this.bcomment = bcomment;
	}

	@Column(name = "bcommentid")
	public Integer getBcommentid() {
		return this.bcommentid;
	}

	public void setBcommentid(Integer bcommentid) {
		this.bcommentid = bcommentid;
	}

}
