package com.works.model;
// Generated 25.Eyl.2019 00:10:58 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Blog generated by hbm2java
 */
@Entity
@Table(name = "blog", catalog = "foodtown")
public class Blog implements java.io.Serializable {

	private Integer bid;
	private String btitle;
	private String bimg;
	private String bdesc;
	private String barticle;

	public Blog() {
	}

	public Blog(String btitle, String bimg, String bdesc, String barticle) {
		this.btitle = btitle;
		this.bimg = bimg;
		this.bdesc = bdesc;
		this.barticle = barticle;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "bid", unique = true, nullable = false)
	public Integer getBid() {
		return this.bid;
	}

	public void setBid(Integer bid) {
		this.bid = bid;
	}

	@Column(name = "btitle")
	public String getBtitle() {
		return this.btitle;
	}

	public void setBtitle(String btitle) {
		this.btitle = btitle;
	}

	@Column(name = "bimg")
	public String getBimg() {
		return this.bimg;
	}

	public void setBimg(String bimg) {
		this.bimg = bimg;
	}

	@Column(name = "bdesc")
	public String getBdesc() {
		return this.bdesc;
	}

	public void setBdesc(String bdesc) {
		this.bdesc = bdesc;
	}

	@Column(name = "barticle", length = 65535)
	public String getBarticle() {
		return this.barticle;
	}

	public void setBarticle(String barticle) {
		this.barticle = barticle;
	}

}
