package com.works.model;
// Generated 25.Eyl.2019 00:10:58 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name = "cart", catalog = "foodtown")
public class Cart implements java.io.Serializable {

	private Integer cartid;
	private String cartproduct;
	private Integer cartquantity;
	private Double cartprize;
	private String cartimg;

	public Cart() {
	}

	public Cart(String cartproduct, Integer cartquantity, Double cartprize, String cartimg) {
		this.cartproduct = cartproduct;
		this.cartquantity = cartquantity;
		this.cartprize = cartprize;
		this.cartimg = cartimg;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cartid", unique = true, nullable = false)
	public Integer getCartid() {
		return this.cartid;
	}

	public void setCartid(Integer cartid) {
		this.cartid = cartid;
	}

	@Column(name = "cartproduct")
	public String getCartproduct() {
		return this.cartproduct;
	}

	public void setCartproduct(String cartproduct) {
		this.cartproduct = cartproduct;
	}

	@Column(name = "cartquantity")
	public Integer getCartquantity() {
		return this.cartquantity;
	}

	public void setCartquantity(Integer cartquantity) {
		this.cartquantity = cartquantity;
	}

	@Column(name = "cartprize", precision = 11, scale = 0)
	public Double getCartprize() {
		return this.cartprize;
	}

	public void setCartprize(Double cartprize) {
		this.cartprize = cartprize;
	}

	@Column(name = "cartimg")
	public String getCartimg() {
		return this.cartimg;
	}

	public void setCartimg(String cartimg) {
		this.cartimg = cartimg;
	}

}
