package com.works.model;
// Generated 25.Eyl.2019 00:10:58 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "order", catalog = "foodtown")
public class Order implements java.io.Serializable {

	private Integer oid;
	private Double ototalprize;
	private Integer ototalquantity;
	private String statu;
	private Integer uid;

	public Order() {
	}

	public Order(Double ototalprize, Integer ototalquantity, String statu, Integer uid) {
		this.ototalprize = ototalprize;
		this.ototalquantity = ototalquantity;
		this.statu = statu;
		this.uid = uid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "oid", unique = true, nullable = false)
	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	@Column(name = "ototalprize", precision = 255, scale = 0)
	public Double getOtotalprize() {
		return this.ototalprize;
	}

	public void setOtotalprize(Double ototalprize) {
		this.ototalprize = ototalprize;
	}

	@Column(name = "ototalquantity")
	public Integer getOtotalquantity() {
		return this.ototalquantity;
	}

	public void setOtotalquantity(Integer ototalquantity) {
		this.ototalquantity = ototalquantity;
	}

	@Column(name = "statu")
	public String getStatu() {
		return this.statu;
	}

	public void setStatu(String statu) {
		this.statu = statu;
	}

	@Column(name = "uid")
	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

}
