package com.works.model;
// Generated 25.Eyl.2019 00:10:58 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OrderTable generated by hbm2java
 */
@Entity
@Table(name = "order_table", catalog = "foodtown")
public class OrderTable implements java.io.Serializable {

	private Integer oid;
	private Double ototalprize;
	private int ototalquantity;
	private String statu;
	private String uname;

	public OrderTable() {
	}

	public OrderTable(int ototalquantity, String statu, String uname) {
		this.ototalquantity = ototalquantity;
		this.statu = statu;
		this.uname = uname;
	}

	public OrderTable(Double ototalprize, int ototalquantity, String statu, String uname) {
		this.ototalprize = ototalprize;
		this.ototalquantity = ototalquantity;
		this.statu = statu;
		this.uname = uname;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "oid", unique = true, nullable = false)
	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	@Column(name = "ototalprize", precision = 255, scale = 0)
	public Double getOtotalprize() {
		return this.ototalprize;
	}

	public void setOtotalprize(Double ototalprize) {
		this.ototalprize = ototalprize;
	}

	@Column(name = "ototalquantity", nullable = false)
	public int getOtotalquantity() {
		return this.ototalquantity;
	}

	public void setOtotalquantity(int ototalquantity) {
		this.ototalquantity = ototalquantity;
	}

	@Column(name = "statu", nullable = false)
	public String getStatu() {
		return this.statu;
	}

	public void setStatu(String statu) {
		this.statu = statu;
	}

	@Column(name = "uname", nullable = false)
	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

}
