package com.works.model;
// Generated 25.Eyl.2019 00:10:58 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProductTable generated by hbm2java
 */
@Entity
@Table(name = "product_table", catalog = "foodtown")
public class ProductTable implements java.io.Serializable {

	private Integer pid;
	private String pname;
	private String pimg;
	private String pprize;
	private String cname;

	public ProductTable() {
	}

	public ProductTable(String pname, String pimg, String pprize, String cname) {
		this.pname = pname;
		this.pimg = pimg;
		this.pprize = pprize;
		this.cname = cname;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "pid", unique = true, nullable = false)
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	@Column(name = "pname", nullable = false)
	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	@Column(name = "pimg", nullable = false)
	public String getPimg() {
		return this.pimg;
	}

	public void setPimg(String pimg) {
		this.pimg = pimg;
	}

	@Column(name = "pprize", nullable = false)
	public String getPprize() {
		return this.pprize;
	}

	public void setPprize(String pprize) {
		this.pprize = pprize;
	}

	@Column(name = "cname", nullable = false)
	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

}
