package com.works.model;
// Generated 25.Eyl.2019 00:10:58 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "foodtown")
public class Product implements java.io.Serializable {

	private Integer pid;
	private String pimg;
	private String pname;
	private String pdesc;
	private Double pprize;
	private Integer cid;

	public Product() {
	}

	public Product(String pimg, String pname, String pdesc, Double pprize, Integer cid) {
		this.pimg = pimg;
		this.pname = pname;
		this.pdesc = pdesc;
		this.pprize = pprize;
		this.cid = cid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "pid", unique = true, nullable = false)
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	@Column(name = "pimg")
	public String getPimg() {
		return this.pimg;
	}

	public void setPimg(String pimg) {
		this.pimg = pimg;
	}

	@Column(name = "pname")
	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	@Column(name = "pdesc")
	public String getPdesc() {
		return this.pdesc;
	}

	public void setPdesc(String pdesc) {
		this.pdesc = pdesc;
	}

	@Column(name = "pprize", precision = 11, scale = 0)
	public Double getPprize() {
		return this.pprize;
	}

	public void setPprize(Double pprize) {
		this.pprize = pprize;
	}

	@Column(name = "cid")
	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

}
