package com.works.model;
// Generated 25.Eyl.2019 00:10:58 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "foodtown")
public class User implements java.io.Serializable {

	private Integer uid;
	private String uname;
	private String umail;
	private String upass;

	public User() {
	}

	public User(String uname, String umail, String upass) {
		this.uname = uname;
		this.umail = umail;
		this.upass = upass;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "uid", unique = true, nullable = false)
	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	@Column(name = "uname")
	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	@Column(name = "umail")
	public String getUmail() {
		return this.umail;
	}

	public void setUmail(String umail) {
		this.umail = umail;
	}

	@Column(name = "upass")
	public String getUpass() {
		return this.upass;
	}

	public void setUpass(String upass) {
		this.upass = upass;
	}

}
